# With the help of https://composerize.com/
version: '2.1'
services:
  postgis:
    image: 'mdillon/postgis'
    container_name: postgis
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
    networks:
      - pgnetwork
    volumes:
      - 'pg_data:/var/lib/postgresql'
    ports:
      - '5432:5432'
    hostname: postgis  
    restart: always

  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - '80:80'
    volumes:
      - 'pga4volume:/var/lib/pgadmin'
    container_name: pgadmin4
    networks:
      - pgnetwork
    environment:
      - PGADMIN_DEFAULT_EMAIL=tfgrisco@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=tfg
    depends_on:
      - postgis
  flask:
    build: . # assuming there is a Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/SurveyingPointCode
    links:
      - postgis:postgres 
    container_name: surveying_point_code
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}   
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT} 
    networks:
      - pgnetwork
    restart: always  

volumes:
  pg_data:
    driver: local
  pga4volume:
    driver: local
networks:
  pgnetwork:
    driver: bridge
